name: Tests

on: [push, pull_request]

jobs:
  x64-ubuntu:
    name: X64-ubuntu
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
            manager: sudo apt-get
            packages: -y fd-find tree-sitter-cli
          - os: ubuntu-24.04
            url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
            manager: sudo apt-get
            packages: -y fd-find tree-sitter-cli
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v3
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.url }}-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          ${{ matrix.manager }} update
          ${{ matrix.manager }} install ${{ matrix.packages }}
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIMRUNTIME="${PWD}/_neovim/share/nvim/runtime"
          make test


      - name: Install linters
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # luals
          cd
          gh release download -R sumneko/lua-language-server -p '*-linux-x64.tar.gz' -D lua-language-server
          tar xzf lua-language-server/* -C lua-language-server
          echo "${PWD}/lua-language-server/bin" >> $GITHUB_PATH
          export PATH="${PWD}/lua-language-server/bin:${PATH}"
          lua-language-server --version

          # luacheck
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
          luacheck --version

          # stylua
          gh release download -R JohnnyMorganz/StyLua -p '*-linux-x86_64.zip'
          unzip -d /usr/local/bin stylua-linux-x86_64.zip
          stylua --version

      - name: Lint
        run: make lint
